version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week (on Monday)
    schedule:
      interval: "weekly"
      day: "monday"
    # Set pull request limits
    open-pull-requests-limit: 10
    # Assign someone to review the PR
    assignees:
      - "miracleonyenma"
    # Add labels to the PRs
    labels:
      - "dependencies"
      - "npm"
    # Set the versioning strategy
    versioning-strategy: auto
    # Group certain dependencies together
    groups:
      development-dependencies:
        dependency-type: "development"
      production-dependencies:
        dependency-type: "production"